apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfaas-nats-connector
  labels:
    app: nats-connector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nats-connector
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nats-connector
        image: affixxx/openfaas-nats-connector:latest
        env:
          - name: NATS_HOST
            value: nats://nats-server:4222
          - name: FAAS_GATEWAY
            value: http://gateway:8080